{{- if .Values.clickhouse.enabled }}
# This requires Altinity ClickHouse operator to be installed first:
# helm repo add clickhouse-operator https://helm.altinity.com
# helm install clickhouse-operator clickhouse-operator/altinity-clickhouse-operator
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: clickhouse-arl
  namespace: {{ .Release.Namespace }}
spec:
  configuration:
    users:
      {{ .Values.clickhouse.username }}/password: {{ .Values.clickhouse.password | default "" | quote }}
      {{ .Values.clickhouse.username }}/networks/ip:
        - "::/0"
    clusters:
      - name: arl-cluster
        layout:
          shardsCount: 1
          replicasCount: 1
    zookeeper:
      nodes:
        - host: zookeeper
          port: 2181
  defaults:
    templates:
      podTemplate: pod-template
      dataVolumeClaimTemplate: data-volume-template
      {{- if .Values.clickhouse.serviceType }}
      serviceTemplate: service-template
      {{- end }}
  templates:
    {{- if .Values.clickhouse.serviceType }}
    serviceTemplates:
      - name: service-template
        spec:
          type: {{ .Values.clickhouse.serviceType }}
          {{- if eq .Values.clickhouse.serviceType "NodePort" }}
          ports:
            - name: http
              port: 8123
              nodePort: {{ .Values.clickhouse.httpNodePort | default 30123 }}
            - name: native
              port: 9000
              nodePort: {{ .Values.clickhouse.nativeNodePort | default 30000 }}
          {{- end }}
    {{- end }}
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              resources:
                requests:
                  memory: "2Gi"
                  cpu: "500m"
                limits:
                  memory: "4Gi"
                  cpu: "1000m"
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: {{ .Values.clickhouse.storageClassName | quote }}
          resources:
            requests:
              storage: {{ .Values.clickhouse.storageSize | default "10Gi" | quote }}
{{- end }}
