{{- if or .Values.clickhouse.enabled .Values.clickhouse.external.host }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arl-operator.fullname" . }}-clickhouse
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arl-operator.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.clickhouse.password | b64enc | quote }}
{{- end }}
