{{- if and .Values.metrics.service.enabled .Values.metrics.prometheusServiceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "arl-operator.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arl-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.prometheusServiceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "arl-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: operator
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.prometheusServiceMonitor.interval }}
      path: /metrics
      relabelings:
        - targetLabel: cluster
          replacement: {{ .Release.Namespace }}
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
---
{{- if .Values.gateway.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "arl-operator.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arl-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.prometheusServiceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "arl-operator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.prometheusServiceMonitor.interval }}
      path: /metrics
      relabelings:
        - targetLabel: cluster
          replacement: {{ .Release.Namespace }}
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
{{- end }}
{{- end }}
